routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Middleware\AksesMenu;
use App\Http\Middleware\Authenticate;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\JsController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PeriodeController;
use App\Http\Controllers\StandarController;
use App\Http\Controllers\PertanyaanController;
use App\Http\Controllers\JawabanController;
use App\Http\Controllers\NcrController;
use App\Http\Controllers\AbrController;
use App\Http\Controllers\PenugasanAuditorController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\BeritaAcaraController;
use App\Http\Controllers\UnggahController;

// Frontend
Route::get('/', [FrontendController::class, 'index'])->name('frontend');
Route::get('/frontend/lihat/{id_unit}', [FrontendController::class, 'lihat']);
// #end Frontend

Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::get('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('adan/{folder}/{file}', [JsController::class, 'backend']);
Route::get('adan/{folder}/{id}/{file}', [JsController::class, 'backendWithId']);

Auth::routes();
Route::get('edit_profile/{id}', [UsersController::class, 'editProfile'])->name('editProfile');
Route::put('update_profile/{id}', [UsersController::class, 'update_profile'])->name('update_profile');
Route::put('update_unit_auditor/{id}', [UsersController::class, 'update_unit_auditor'])->name('update_unit_auditor');
Route::get('reset_auditee', [UsersController::class, 'reset_auditee'])->name('reset_auditee');
Route::middleware([Authenticate::class, AksesMenu::class])->group(function () {
    #dashboard
	Route::group([ 'prefix' => 'dashboard', 'as' => 'dashboard.'], function () {
        Route::get('/', [HomeController::class, 'index']);
        Route::any('data_monitoring/{periode?}', [HomeController::class, 'data_monitoring'])->name('data_monitoring');
        Route::any('data_monitoring_prodi', [HomeController::class, 'data_monitoring_prodi'])->name('data_monitoring_prodi');
        Route::post('cetak', [BeritaAcaraController::class, 'cetak'])->name('berita_acara');

	});

    #users
	Route::group([ 'prefix' => 'users', 'as' => 'users.'], function () {
		Route::get('hapus/{id}', [UsersController::class, 'hapus'])->name('hapus');
		Route::any('data', [UsersController::class, 'data'])->name('data');
	});
    Route::resource('users', UsersController::class);

    #permission
	Route::group([ 'prefix' => 'permission', 'as' => 'permission.'], function () {
		Route::get('hapus/{id}', [PermissionController::class, 'hapus'])->name('hapus');
		Route::any('data', [PermissionController::class, 'data'])->name('data');
	});
    Route::resource('permission', PermissionController::class);

    #menu
	Route::group([ 'prefix' => 'menu', 'as' => 'menu.'], function () {
		Route::get('hapus/{id}', [MenuController::class, 'hapus'])->name('hapus');
		Route::any('data', [MenuController::class, 'data'])->name('data');
	});
    Route::resource('menu', MenuController::class);

    #standar
	Route::group([ 'prefix' => 'standar', 'as' => 'standar.'], function () {
		Route::get('hapus/{id}', [StandarController::class, 'hapus'])->name('hapus');
		Route::any('data', [StandarController::class, 'data'])->name('data');
	});
    Route::resource('standar', StandarController::class);

    #penugasan
	Route::group([ 'prefix' => 'penugasan', 'as' => 'penugasan.'], function () {
		Route::get('hapus/{id}', [PenugasanAuditorController::class, 'hapus'])->name('hapus');
		Route::any('data', [PenugasanAuditorController::class, 'data'])->name('data');
	});
    Route::resource('penugasan', PenugasanAuditorController::class);

    #pertanyaan
	Route::group([ 'prefix' => 'pertanyaan', 'as' => 'pertanyaan.'], function () {
		Route::get('hapus/{id}', [PertanyaanController::class, 'hapus'])->name('hapus');
		Route::any('data', [PertanyaanController::class, 'data'])->name('data');
	});
    Route::resource('pertanyaan', PertanyaanController::class);

    #periode
	Route::group([ 'prefix' => 'periode', 'as' => 'periode.'], function () {
		Route::get('hapus/{id}', [PeriodeController::class, 'hapus'])->name('hapus');
		Route::get('pesan', [PeriodeController::class, 'pesan'])->name('pesan');
		Route::post('kirim_pesan', [PeriodeController::class, 'kirim_pesan'])->name('kirim_pesan');
		Route::any('data', [PeriodeController::class, 'data'])->name('data');
	});
    Route::resource('periode', PeriodeController::class);

    #instrumen
	Route::group([ 'prefix' => 'instrumen', 'as' => 'instrumen.'], function () {
		Route::get('standar/{id}', [JawabanController::class, 'standar'])->name('standar');
		Route::post('simpan_jawaban', [JawabanController::class, 'simpan_jawaban'])->name('simpan');
		Route::get('disable/{id?}', [JawabanController::class, 'nonaktif'])->name('disable');
		Route::post('ambil_pilihan', [JawabanController::class, 'ambil_pilihan'])->name('ambil_pilihan');
		Route::get('ambil_file/{file}', [JawabanController::class, 'ambil_file'])->name('ambil_file');
		Route::post('publish', [JawabanController::class, 'publis'])->name('publish');
    });

    #ncr
	Route::group([ 'prefix' => 'ncr', 'as' => 'ncr.'], function () {
        Route::get('ambil_file/{file}', [NcrController::class, 'ambil_file'])->name('ambil_file');
        Route::get('ambil_file_konfirmasi/{file}', [NcrController::class, 'ambil_file_konfirmasi'])->name('ambil_file_konfirmasi');
        Route::get('ambil_file_ncr/{file}', [NcrController::class, 'ambil_file_ncr'])->name('ambil_file_ncr');
        Route::get('standar/{id}/{periode?}', [NcrController::class, 'standar'])->name('standar');
        Route::get('tindakan/{id}', [NcrController::class, 'tindakan'])->name('tindakan');
        Route::get('penyebab/{id}', [NcrController::class, 'penyebab'])->name('penyebab');
        Route::get('catatan-verifikasi/{id}', [NcrController::class, 'catatan_verifikasi'])->name('catatan_verifikasi');
        Route::get('pencegahan/{id}', [NcrController::class, 'pencegahan'])->name('pencegahan');
        Route::get('prodikoreksi/{id}', [NcrController::class, 'prodikoreksi'])->name('prodikoreksi');
        Route::get('reupload/{id}', [NcrController::class, 'reupload'])->name('reupload');
        Route::get('verifikasi/{id}', [NcrController::class, 'verifikasi'])->name('verifikasi');
        Route::get('nilai/{id}', [NcrController::class, 'nilai'])->name('nilai');
        Route::get('unggah/{id}', [NcrController::class, 'unggah'])->name('unggah');
        Route::any('unggah_file/{id}', [NcrController::class, 'unggah_file'])->name('unggah_file');
        Route::any('cetak/{id}/{periode?}', [NcrController::class, 'cetak'])->name('cetak');
	});
	Route::resource('ncr', NcrController::class);

    #abr
	Route::group([ 'prefix' => 'abr', 'as' => 'abr.'], function () {
        Route::get('/{periode?}', [AbrController::class, 'index']);
        Route::get('ambil_file/{id}', [AbrController::class, 'ambil_file'])->name('ambil_file');
        Route::get('standar/{id}', [AbrController::class, 'standar'])->name('standar');
        Route::any('cetak/{periode?}', [AbrController::class, 'cetak'])->name('cetak');
        Route::any('ditandatangani/{periode?}', [AbrController::class, 'ditandatangani'])->name('ditandatangani');
        Route::any('tindakan/{id}', [AbrController::class, 'tindakan'])->name('tindakan');
        Route::get('modal_unggah/{id}', [AbrController::class, 'modal_unggah'])->name('modal_unggah');
        Route::any('unggah', [AbrController::class, 'unggah'])->name('unggah');
	});
	Route::resource('abr', AbrController::class);

    #unggah
	Route::group([ 'prefix' => 'unggah', 'as' => 'unggah.'], function () {
        Route::any('data', [UnggahController::class, 'data'])->name('data');
        Route::get('ambil_file/{id}', [UnggahController::class, 'ambil_file'])->name('ambil_file');
        Route::get('modal_unggah/{id}', [UnggahController::class, 'modal_unggah'])->name('modal_unggah');
        Route::any('unggah', [UnggahController::class, 'unggah'])->name('unggah');
		Route::get('hapus/{id}', [UnggahController::class, 'hapus'])->name('hapus');
	});
	Route::resource('unggah', UnggahController::class);


});


Route::get('/{page?}', [AdminController::class, 'index']);

resources/views/backend/penugasan/ajax.blade.php
$(document).on("click",".submit-tambah",function() {
	var dataString			= $('#frmAdan').serializeArray();
	var url					= "{{ url($url_admin.'/penugasan') }}";
	goAjax(url, dataString);
});

$( ".submit-ubah" ).click(function() {
	var dataString			= $("#frmAdan-ubah").serializeArray();
	var url					= "{{ url($url_admin.'/penugasan') }}/"+$("#id").val();
	goAjax(url, dataString);
});
$( ".submit-hapus" ).click(function() {
	var url					= "{{ url($url_admin.'/penugasan') }}/"+$("#id").val();
	var dataString			= $('#frmAdan').serializeArray();
	goAjax(url, dataString);
});

resources/views/backend/penugasan/hapus.blade.php
{!! Form::open(array('id' => 'frmAdan', 'class' => 'form account-form', 'method' => 'DELETE')) !!}
<div class="row">
		<div class="col-md-12">
			<p>
				<label class="control-label">Hapus data <strong>ini ?</strong></label>
				{!! Form::hidden('id', $data->id, array('id' => 'id')) !!}
				{!! Form::hidden('url', URL::previous(), array('id' => 'url')) !!}
			</p>
		</div>
</div>
<div class="row">
		<div class="col-md-12">
				<span class="pesan"></span>
		</div>
</div>
{!! Form::close() !!}
<script src="{{ URL::asset('adan/penugasan/ajax.js') }}"></script>
<script src="{{ URL::asset('adan/script/ajax.js') }}"></script>

resources/views/backend/penugasan/index.blade.php
@extends('layouts.master')
@section('css')
<link href="{{ URL::asset('assets/plugins/datatable/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
<link href="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/daterangepicker.css')}}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/date-picker/spectrum.css')}}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/fileuploads/css/fileupload.css')}}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/multipleselect/multiple-select.css')}}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/select2/select2.min.css')}}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/time-picker/jquery.timepicker.css')}}" rel="stylesheet" />
@endsection

@section('page-header')
<!-- PAGE-HEADER -->
    <div>
        <h1 class="page-title">{{$halaman->nama}}</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">{{$parent->nama}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{$halaman->nama}}</li>
        </ol>
    </div>
<!-- PAGE-HEADER END -->
@endsection
@section('content')
<!-- ROW-1 OPEN -->
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <div class="row col-md-12">
                    <div class="col-md-10">
                        <h3 class="card-title">{{$halaman->nama}}</h3>
                    </div>
                    <div class="col-md-2 col-sm-2 col-2 text-right">
                        <div class="btn-group">
                            <a class="btn btn-secondary-light btn-sm tambah mr-2">Tambah <i class="fa fa-plus"></i></a>

                            {{-- <a class="btn btn-info-light btn-sm">Kirim Pesan <i class="fa fa-envelope"></i></a> --}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">

                <div class="table-responsive">
                    <table id="table" class="table table-striped table-bordered text-nowrap w-100">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama Auditor</th>
                                <th>Unit Auditee</th>
                                <th>Posisi</th>
                                <th>Periode</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- TABLE WRAPPER -->
        </div>
        <!-- SECTION WRAPPER -->
    </div>
</div>
<!-- ROW-1 CLOSED -->

</div>
</div>
<!-- CONTAINER CLOSED -->
</div>
@endsection

@section('js')
<script src="{{ URL::asset('assets/plugins/datatable/jquery.dataTables.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/datatable.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/datatable-2.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/dataTables.responsive.min.js') }}"></script>
<script src="{{ URL::to('/') }}/adan/penugasan/jquery.js"></script>
<script>
    var table;
    $(document).ready( function () {
            $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
            });
        table = $('#table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
            url: '{!! route('penugasan.data') !!}',
            type: 'POST'
            },
            columns: [
                { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false,searchable: false},
                { data: 'nama_auditor' },
                { data: 'unit_auditee'},
                { data: 'posisi'},
                { data: 'periode.nama_periode'},
                { data: 'actions', name: 'actions', orderable: false, searchable: false }
            ]
        });
        table.on( 'draw', function () {
            $('.livicon').each(function(){
                $(this).updateLivicon();
            });
        } );
    });
    </script>


@endsection

resources/views/backend/penugasan/jquery.blade.php
$(document).ready(function(){
   $('.tambah').click(function(){
		adanLoadingFadeIn();
		$.loadmodal({
			url: "{{ url($url_admin.'/penugasan/create') }}",
			id: 'responsive',
			dlgClass: 'fade',
			bgClass: 'primary',
			title: 'Tambah',
			width: '700px',
			modal: {
				keyboard: true,
				// any other options from the regular $().modal call (see Bootstrap docs)
				},
          ajax: {
				dataType: 'html',
				method: 'GET',
				success: function(data, status, xhr){
                    adanLoadingFadeOut();
				},

			},
        });
  });

	$(document).on("click",".ubah",function() {
    adanLoadingFadeIn();
		var id = $(this).attr('data-id');
		$.loadmodal({
			url: "{{ url($url_admin.'/penugasan') }}/"+ id +"/edit",
      id: 'responsive',
			dlgClass: 'fade',
			bgClass: 'warning',
			title: 'Ubah',
			width: '700px',
			modal: {
				keyboard: true,
				// any other options from the regular $().modal call (see Bootstrap docs)
				},
          ajax: {
				dataType: 'html',
				method: 'GET',
				success: function(data, status, xhr){
            adanLoadingFadeOut();
				},
			},
        });
	});

	$(document).on("click",".hapus",function() {
    adanLoadingFadeIn();
		var id = $(this).attr('data-id');
		$.loadmodal({
			url: "{{ url($url_admin.'/penugasan/hapus') }}/"+ id,
      id: 'responsive',
			dlgClass: 'fade',
			bgClass: 'danger',
			title: 'Hapus',
			width: '300px',
			modal: {
				keyboard: true,
				// any other options from the regular $().modal call (see Bootstrap docs)
				},
          ajax: {
				dataType: 'html',
				method: 'GET',
				success: function(data, status, xhr){
            adanLoadingFadeOut();
				},
			},
        });
	});

});

resources/views/backend/penugasan/tambah.blade.php
<link href="{{ URL::to('/') }}/assets/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
<link href="{{ URL::asset('assets/plugins/select2/select2.min.css')}}" rel="stylesheet" />
{!! Form::open(array('id' => 'frmAdan', 'class' => 'form account-form', 'method' => 'post', 'files' => true)) !!}


        <div class="form-group row" >
            {!! Form::label('Nama Auditor', 'Nama Auditor *', array('class' => 'col-md-4 form-label')) !!}
            <div class="col-md-12">
            {!! Form::select('user_id', $auditor, NULL, array('id' => 'user_id', 'class' => 'form-control select2', 'placeholder' => 'Pilih', 'style' => 'width:100%')) !!}
            </div>
        </div>
        <div class="form-group row">
            {!! Form::label('Unit Auditee', 'Unit Auditee *', array('class' => 'col-md-4 form-label')) !!}
            <div class="col-md-12">
            {!! Form::select('unit_audit_id', $unit, NULL, array('id' => 'unit_audit_id', 'class' => 'form-control select2', 'placeholder' => 'Pilih', 'style' => 'width:100%')) !!}
            </div>
        </div>
        <div class="form-group row">
            {!! Form::label('Periode', 'Periode *', array('class' => 'col-md-4 form-label')) !!}
            <div class="col-md-12">
            {!! Form::select('periode_id', $periode, NULL, array('id' => 'periode_id', 'class' => 'form-control select2', 'placeholder' => 'Pilih', 'style' => 'width:100%')) !!}
            </div>
        </div>
        <div class="form-group row">
            {!! Form::label('Posisi', 'Posisi *', array('class' => 'col-md-4 form-label')) !!}
            <div class="col-md-12">
            {!! Form::select('posisi', ['Ketua' => 'Ketua', 'Anggota' => 'Anggota'], NULL, array('id' => 'posisi', 'class' => 'form-control select2', 'placeholder' => 'Pilih', 'style' => 'width:100%')) !!}
            </div>
        </div>


	{!! Form::hidden('url', URL::previous(), array('id' => 'url')) !!}

<div class="row">
	<div class="col-md-12">
		<span class="pesan"></span>
	</div>
</div>
{!! Form::close() !!}
<script src="{{ URL::asset('adan/penugasan/ajax.js') }}"></script>
<script src="{{ URL::asset('adan/script/ajax.js') }}"></script>

<script src="{{ URL::to('/') }}/assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js" ></script>
<script src="{{ URL::to('/') }}/assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker-init.js" ></script>
<script src="{{ URL::asset('assets/plugins/select2/select2.full.min.js') }}"></script>

<script>
	$('.select2').select2();

</script>

resources/views/backend/penugasan/ubah.blade.php
<link href="{{ URL::to('/') }}/assets/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
<link href="{{ URL::asset('assets/plugins/select2/select2.min.css')}}" rel="stylesheet" />
{!! Form::open(array('id' => 'frmAdan-ubah', 'class' => 'form account-form', 'method' => 'PUT')) !!}
{{ csrf_field() }}
<div class="form-group row" >
    {!! Form::label('Nama Auditor', 'Nama Auditor *', array('class' => 'col-md-4 form-label')) !!}
    <div class="col-md-12">
    {!! Form::select('user_id', $auditor, $data->user_id, array('id' => 'user_id', 'class' => 'form-control select2', 'placeholder' => 'Pilih', 'style' => 'width:100%')) !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('Unit Auditee', 'Unit Auditee *', array('class' => 'col-md-4 form-label')) !!}
    <div class="col-md-12">
    {!! Form::select('unit_audit_id', $unit, $data->unit_audit_id, array('id' => 'unit_audit_id', 'class' => 'form-control select2', 'placeholder' => 'Pilih', 'style' => 'width:100%')) !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('Periode', 'Periode *', array('class' => 'col-md-4 form-label')) !!}
    <div class="col-md-12">
    {!! Form::select('periode_id', $periode, $data->periode_id, array('id' => 'periode_id', 'class' => 'form-control select2', 'placeholder' => 'Pilih', 'style' => 'width:100%')) !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('Posisi', 'Posisi *', array('class' => 'col-md-4 form-label')) !!}
    <div class="col-md-12">
    {!! Form::select('posisi', ['Ketua' => 'Ketua', 'Anggota' => 'Anggota'], $data->posisi, array('id' => 'posisi', 'class' => 'form-control select2', 'placeholder' => 'Pilih', 'style' => 'width:100%')) !!}
    </div>
</div>

	{!! Form::hidden('id', $data->id, array('id' => 'id')) !!}
	{!! Form::hidden('url', URL::previous(), array('id' => 'url')) !!}
</div>
<div class="row">
		<div class="col-md-12">
			<span class="pesan"></span>
		</div>
</div>
{!! Form::close() !!}
<script src="{{ URL::asset('adan/penugasan/ajax.js') }}"></script>
<script src="{{ URL::asset('adan/script/ajax.js') }}"></script>

<script src="{{ URL::to('/') }}/assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js" ></script>
<script src="{{ URL::to('/') }}/assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker-init.js" ></script>
<script src="{{ URL::asset('assets/plugins/select2/select2.full.min.js') }}"></script>

<script>
	$('.select2').select2();

</script>