routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Middleware\AksesMenu;
use App\Http\Middleware\Authenticate;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\JsController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PeriodeController;
use App\Http\Controllers\StandarController;
use App\Http\Controllers\PertanyaanController;
use App\Http\Controllers\JawabanController;
use App\Http\Controllers\NcrController;
use App\Http\Controllers\AbrController;
use App\Http\Controllers\PenugasanAuditorController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\BeritaAcaraController;
use App\Http\Controllers\UnggahController;

// Frontend
Route::get('/', [FrontendController::class, 'index'])->name('frontend');
Route::get('/frontend/lihat/{id_unit}', [FrontendController::class, 'lihat']);
// #end Frontend

Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::get('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('adan/{folder}/{file}', [JsController::class, 'backend']);
Route::get('adan/{folder}/{id}/{file}', [JsController::class, 'backendWithId']);

Auth::routes();
Route::get('edit_profile/{id}', [UsersController::class, 'editProfile'])->name('editProfile');
Route::put('update_profile/{id}', [UsersController::class, 'update_profile'])->name('update_profile');
Route::put('update_unit_auditor/{id}', [UsersController::class, 'update_unit_auditor'])->name('update_unit_auditor');
Route::get('reset_auditee', [UsersController::class, 'reset_auditee'])->name('reset_auditee');
Route::middleware([Authenticate::class, AksesMenu::class])->group(function () {
    #dashboard
	Route::group([ 'prefix' => 'dashboard', 'as' => 'dashboard.'], function () {
        Route::get('/', [HomeController::class, 'index']);
        Route::any('data_monitoring/{periode?}', [HomeController::class, 'data_monitoring'])->name('data_monitoring');
        Route::any('data_monitoring_prodi', [HomeController::class, 'data_monitoring_prodi'])->name('data_monitoring_prodi');
        Route::post('cetak', [BeritaAcaraController::class, 'cetak'])->name('berita_acara');

	});

    #users
	Route::group([ 'prefix' => 'users', 'as' => 'users.'], function () {
		Route::get('hapus/{id}', [UsersController::class, 'hapus'])->name('hapus');
		Route::any('data', [UsersController::class, 'data'])->name('data');
	});
    Route::resource('users', UsersController::class);

    #permission
	Route::group([ 'prefix' => 'permission', 'as' => 'permission.'], function () {
		Route::get('hapus/{id}', [PermissionController::class, 'hapus'])->name('hapus');
		Route::any('data', [PermissionController::class, 'data'])->name('data');
	});
    Route::resource('permission', PermissionController::class);

    #menu
	Route::group([ 'prefix' => 'menu', 'as' => 'menu.'], function () {
		Route::get('hapus/{id}', [MenuController::class, 'hapus'])->name('hapus');
		Route::any('data', [MenuController::class, 'data'])->name('data');
	});
    Route::resource('menu', MenuController::class);

    #standar
	Route::group([ 'prefix' => 'standar', 'as' => 'standar.'], function () {
		Route::get('hapus/{id}', [StandarController::class, 'hapus'])->name('hapus');
		Route::any('data', [StandarController::class, 'data'])->name('data');
	});
    Route::resource('standar', StandarController::class);

    #penugasan
	Route::group([ 'prefix' => 'penugasan', 'as' => 'penugasan.'], function () {
		Route::get('hapus/{id}', [PenugasanAuditorController::class, 'hapus'])->name('hapus');
		Route::any('data', [PenugasanAuditorController::class, 'data'])->name('data');
	});
    Route::resource('penugasan', PenugasanAuditorController::class);

    #pertanyaan
	Route::group([ 'prefix' => 'pertanyaan', 'as' => 'pertanyaan.'], function () {
		Route::get('hapus/{id}', [PertanyaanController::class, 'hapus'])->name('hapus');
		Route::any('data', [PertanyaanController::class, 'data'])->name('data');
	});
    Route::resource('pertanyaan', PertanyaanController::class);

    #periode
	Route::group([ 'prefix' => 'periode', 'as' => 'periode.'], function () {
		Route::get('hapus/{id}', [PeriodeController::class, 'hapus'])->name('hapus');
		Route::get('pesan', [PeriodeController::class, 'pesan'])->name('pesan');
		Route::post('kirim_pesan', [PeriodeController::class, 'kirim_pesan'])->name('kirim_pesan');
		Route::any('data', [PeriodeController::class, 'data'])->name('data');
	});
    Route::resource('periode', PeriodeController::class);

    #instrumen
	Route::group([ 'prefix' => 'instrumen', 'as' => 'instrumen.'], function () {
		Route::get('standar/{id}', [JawabanController::class, 'standar'])->name('standar');
		Route::post('simpan_jawaban', [JawabanController::class, 'simpan_jawaban'])->name('simpan');
		Route::get('disable/{id?}', [JawabanController::class, 'nonaktif'])->name('disable');
		Route::post('ambil_pilihan', [JawabanController::class, 'ambil_pilihan'])->name('ambil_pilihan');
		Route::get('ambil_file/{file}', [JawabanController::class, 'ambil_file'])->name('ambil_file');
		Route::post('publish', [JawabanController::class, 'publis'])->name('publish');
    });

    #ncr
	Route::group([ 'prefix' => 'ncr', 'as' => 'ncr.'], function () {
        Route::get('ambil_file/{file}', [NcrController::class, 'ambil_file'])->name('ambil_file');
        Route::get('ambil_file_konfirmasi/{file}', [NcrController::class, 'ambil_file_konfirmasi'])->name('ambil_file_konfirmasi');
        Route::get('ambil_file_ncr/{file}', [NcrController::class, 'ambil_file_ncr'])->name('ambil_file_ncr');
        Route::get('standar/{id}/{periode?}', [NcrController::class, 'standar'])->name('standar');
        Route::get('tindakan/{id}', [NcrController::class, 'tindakan'])->name('tindakan');
        Route::get('penyebab/{id}', [NcrController::class, 'penyebab'])->name('penyebab');
        Route::get('catatan-verifikasi/{id}', [NcrController::class, 'catatan_verifikasi'])->name('catatan_verifikasi');
        Route::get('pencegahan/{id}', [NcrController::class, 'pencegahan'])->name('pencegahan');
        Route::get('prodikoreksi/{id}', [NcrController::class, 'prodikoreksi'])->name('prodikoreksi');
        Route::get('reupload/{id}', [NcrController::class, 'reupload'])->name('reupload');
        Route::get('verifikasi/{id}', [NcrController::class, 'verifikasi'])->name('verifikasi');
        Route::get('nilai/{id}', [NcrController::class, 'nilai'])->name('nilai');
        Route::get('unggah/{id}', [NcrController::class, 'unggah'])->name('unggah');
        Route::any('unggah_file/{id}', [NcrController::class, 'unggah_file'])->name('unggah_file');
        Route::any('cetak/{id}/{periode?}', [NcrController::class, 'cetak'])->name('cetak');
	});
	Route::resource('ncr', NcrController::class);

    #abr
	Route::group([ 'prefix' => 'abr', 'as' => 'abr.'], function () {
        Route::get('/{periode?}', [AbrController::class, 'index']);
        Route::get('ambil_file/{id}', [AbrController::class, 'ambil_file'])->name('ambil_file');
        Route::get('standar/{id}', [AbrController::class, 'standar'])->name('standar');
        Route::any('cetak/{periode?}', [AbrController::class, 'cetak'])->name('cetak');
        Route::any('ditandatangani/{periode?}', [AbrController::class, 'ditandatangani'])->name('ditandatangani');
        Route::any('tindakan/{id}', [AbrController::class, 'tindakan'])->name('tindakan');
        Route::get('modal_unggah/{id}', [AbrController::class, 'modal_unggah'])->name('modal_unggah');
        Route::any('unggah', [AbrController::class, 'unggah'])->name('unggah');
	});
	Route::resource('abr', AbrController::class);

    #unggah
	Route::group([ 'prefix' => 'unggah', 'as' => 'unggah.'], function () {
        Route::any('data', [UnggahController::class, 'data'])->name('data');
        Route::get('ambil_file/{id}', [UnggahController::class, 'ambil_file'])->name('ambil_file');
        Route::get('modal_unggah/{id}', [UnggahController::class, 'modal_unggah'])->name('modal_unggah');
        Route::any('unggah', [UnggahController::class, 'unggah'])->name('unggah');
		Route::get('hapus/{id}', [UnggahController::class, 'hapus'])->name('hapus');
	});
	Route::resource('unggah', UnggahController::class);


});


Route::get('/{page?}', [AdminController::class, 'index']);

app/Http/Controllers/UnggahController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Dokumen;
use App\Models\Unit;
use App\Models\Periode;
use Auth;
use Illuminate\Config;
use Illuminate\Http\Request;
use Redirect;
use View;
use Yajra\DataTables\DataTables;
use Validator;
use DB;

class UnggahController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pilihUnitAuditee   = Unit::select("units.id", \DB::raw("CONCAT(units.nama_unit,' - ',units.jenjang_pendidikan) as nama_prodi"))->whereNotNull('parent_id')->pluck('nama_prodi', 'id');
        $pilihPeriode       = Periode::select('nama_periode','id')->pluck('nama_periode','id');

        return view('backend.unggah.index', compact('pilihUnitAuditee','pilihPeriode'));
    }

    public function data(Request $request)
    {
        $data = Dokumen::with(['periode', 'unit'])
                ->orderBy('id', 'DESC');
                if(Auth::user()->permission_id == 3 || Auth::user()->permission_id == 4){
                    $data->where('unit_id', \Auth::user()->unit_id);
                }
                $data->where('jenis','<>', 'ABR');
        return DataTables::of($data->get())

            ->addColumn('actions',function($data) {
                $actions = '<a data-id="'.$data->id.'"  class="btn btn-outline-warning btn-xs ubah mr-2"><i class="fa fa-pencil"></i></a>';
                $actions .= '<a  data-id="'.$data->id.'" class="btn btn-outline-danger btn-xs hapus"><i class="fa fa-trash-o"></i></a>';
                return $actions;
            })
            ->addColumn('prodi', function (Dokumen $data) {
                return $data->unit->nama_unit.' - '.$data->unit->jenjang_pendidikan;
            })
            ->addColumn('periode', function (Dokumen $data) {
                return $data->periode->nama_periode;
            })
            ->addColumn('file', function (Dokumen $data) {
                // return '<a href="'.url('unggah/ambil_file/'.$data->file).'" target="_blank" class="btn btn-outline-primary btn-sm"> <i class="fa fa-file"></i>'.$data->file.'</a></span>';
                return ($data->urlfile) ? '<a href="'.$data->urlfile.'" target="_blank" class="btn btn-outline-primary btn-sm"> <i class="fa fa-file"></i>Lihat Dokumen</a></span>' : '<span>Belum ada dokumen </span></span>';
            })
            ->addIndexColumn()
            ->rawColumns(['actions','periode','file','prodi'])
            ->make(true);
    }

    public function modal_unggah()
    {
        return view('backend.unggah.unggah');
    }

    public function unggah(Request $request)
    {

        // if ($file = $request->file('pic')) {

                // $dataFile = savegdrive($file);

                // $dataFile = savelocal($file);

                $periode = cekPeriode();

                $update =  Dokumen::updateOrCreate(
                    ['unit_id'      => \Auth::user()->unit_id, 'user_id'  => \Auth::user()->id, 'periode_id' => $periode['id'], 'jenis' => $request->jenis], [
                    // 'file'          => $dataFile,
                    'urlfile'       => $request->urlfile,
                    'jenis'         => $request->jenis,
                    'unit_id'       => \Auth::user()->unit_id,
                    'user_id'       => \Auth::user()->id,
                    'periode_id'    => $periode['id'],
                ]);

        // }else{
        //     $respon = array('status'=>false, 'pesan' => ['msg' => 'Mohon upload dokumen dengan benar !']);
        //     return response()->json($respon);
        // }


        if ($update) {
            $respon = array('status'=>true, 'pesan' => ['msg' => 'Data berhasil diubah']);
        } else {
            $respon = array('status'=>false, 'pesan' => ['msg' => 'Data gagal diubah']);
        }

        return response()->json($respon);
    }


    public function ambil_file($file)
    {
        // return viewgdrive($file);
        return viewlocal($file);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data           = Dokumen::find($id);
        return view('backend.unggah.ubah', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $validator = Validator::make($request->all(), [
            'jenis'              => 'required',
        ],
        [
            'jenis.required'     => 'Harap mengisi form jenis.'
       ]);
        if ($validator->fails()) {
            $respon = array('status'=>false, 'pesan' => $validator->messages());
        } else {
            $data   = Dokumen::find($id);
            $update = $data->update($request->all());

            if ($update) {
                $respon = array('status'=>true, 'pesan' => ['msg' => 'Data berhasil diubah']);
            } else {
                $respon = array('status'=>false, 'pesan' => ['msg' => 'Data gagal diubah']);
            }
        }
        return response()->json($respon);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function hapus($id)
    {
        $data = Dokumen::find($id);
        return view('backend.unggah.hapus', ['data' => $data]);
    }

    public function destroy($id)
    {
        $data = Dokumen::find($id);

        if ($data->delete()) {
            $respon = array('status'=>true, 'pesan' => ['msg' => 'Data berhasil dihapus']);
        } else {
            $respon = array('status'=>false, 'pesan' => ['msg' => 'Data gagal dihapus']);
        }
        return response()->json($respon);
    }
}

resources/views/backend/unggah/ajax.blade.php
$( ".submit-ubah" ).click(function() {
	var dataString			= $("#frmAdan-ubah").serializeArray();
	var url					= "{{ url($url_admin.'/unggah') }}/"+$("#id").val();
	goAjax(url, dataString);
});

$( ".submit-unggah" ).click(function() {
	$('#frmAdan').submit();
});

$( ".submit-hapus" ).click(function() {
	var url					= "{{ url($url_admin.'/unggah') }}/"+$("#id").val();
	var dataString			= $('#frmAdan').serializeArray();
	goAjax(url, dataString);
});

$('#frmAdan').on('submit', function(event){
	event.preventDefault();
	$.ajax({
	url:"{{ url($url_admin.'/unggah/unggah') }}",
	method:"POST",
	enctype: "multipart/form-data",
	data:new FormData(this),
	dataType:'JSON',
	contentType: false,
	cache: false,
	processData: false,
	beforeSend: function(){
				sebelumKirim();
		},
		success: function(data){
				successMsg(data);
		},
		error: function(x, e){
			//	errorMsg(x.status);
		}
	})
});

resources/views/backend/unggah/hapus.blade.php
{!! Form::open(array('id' => 'frmAdan', 'class' => 'form account-form', 'method' => 'DELETE')) !!}
<div class="row">
		<div class="col-md-12">
			<p>
				<label class="control-label">Hapus data <strong>{{ $data->jenis }}?</strong></label>
				{!! Form::hidden('id', $data->id, array('id' => 'id')) !!}
				{!! Form::hidden('url', URL::previous(), array('id' => 'url')) !!}
			</p>
		</div>
</div>
<div class="row">
		<div class="col-md-12">
				<span class="pesan"></span>
		</div>
</div>
{!! Form::close() !!}
<script src="{{ URL::asset('adan/unggah/ajax.js') }}"></script>
<script src="{{ URL::asset('adan/script/ajax.js') }}"></script>

resources/views/backend/unggah/index.blade.php
@extends('layouts.master')
@section('css')
<link href="{{ URL::asset('assets/plugins/datatable/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
<link href="{{ URL::asset('assets/plugins/bootstrap-daterangepicker/daterangepicker.css')}}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/date-picker/spectrum.css')}}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/fileuploads/css/fileupload.css')}}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/multipleselect/multiple-select.css')}}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/select2/select2.min.css')}}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/time-picker/jquery.timepicker.css')}}" rel="stylesheet" />
@endsection

@section('page-header')
<!-- PAGE-HEADER -->
    <div>
        <h1 class="page-title">{{$halaman->nama}}</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Index</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{$halaman->nama}}</li>
        </ol>
    </div>
<!-- PAGE-HEADER END -->
@endsection
@section('content')
<!-- ROW-1 OPEN -->
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <div class="row col-md-12">
                    <div class="col-md-10">
                        <h3 class="card-title">{{$halaman->nama}}
                             {{-- @if(\Auth::user()->permission_id != 4) {{ auditee() ?? null }} @endif {!! ( periode() ?? null) ? periode() : '' !!} --}}
                        </h3>
                    </div>
                    <div class="col-md-2 col-sm-2 col-2 text-right">
                        <div class="btn-group">
                            @if(\Auth::user()->permission_id == 3)
                            <a class="btn btn-secondary-light btn-sm unggah"><i class="fa fa-plus"></i> Unggah Dokumen</a>
                            @endif
                        </div>
                    </div>
                </div>

            </div>
            <div class="card-body">

                <div class="table-responsive">
                    <table id="table" class="table table-striped table-bordered text-nowrap w-100">
                        <thead>
                            <tr>
                                <th>No</th>
                                @if(\Auth::user()->permission_id == 1 || \Auth::user()->permission_id == 2)
                                <th>Program Studi</th>
                                @endif
                                <th>Dokumen</th>
                                <th>Jenis</th>
                                <th>Periode</th>
                                @if(\Auth::user()->permission_id == 3)
                                <th>Aksi</th>
                                @endif
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- TABLE WRAPPER -->
        </div>
        <!-- SECTION WRAPPER -->
    </div>
</div>
<!-- ROW-1 CLOSED -->

</div>
</div>
<!-- CONTAINER CLOSED -->
</div>
@endsection

@section('js')
<script src="{{ URL::asset('assets/plugins/datatable/jquery.dataTables.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/datatable.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/datatable-2.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/dataTables.responsive.min.js') }}"></script>
<script src="{{ URL::to('/') }}/adan/unggah/jquery.js"></script>
<script>
    var table;
    $(document).ready( function () {
            $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
            });
        table = $('#table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
            url: '{!! route('unggah.data') !!}',
            type: 'POST'
            },
            columns: [
                { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false,searchable: false},
                @if(\Auth::user()->permission_id == 1 || \Auth::user()->permission_id == 2)
                { data: 'prodi' },
                @endif
                { data: 'file' },
                { data: 'jenis'},
                { data: 'periode', name: 'periode.nama_periode'},
                @if(\Auth::user()->permission_id == 3)
                { data: 'actions', name: 'actions', orderable: false, searchable: false }
                @endif
            ]
        });
        table.on( 'draw', function () {
            $('.livicon').each(function(){
                $(this).updateLivicon();
            });
        } );
    });
    </script>


{{--
@if(\Auth::user()->permission_id == 1 || \Auth::user()->permission_id == 2)
    @if (\Auth::user()->unit_id === NULL)
    <script type="text/javascript">
        $(document).ready(function(){
            $('#modalPilih_auditee').modal('show');
        });
    </script>
    @else
    <script type="text/javascript">
        $(document).ready(function(){
            $('#modalPilih_auditee').modal('hide');
        });
    </script>
    @endif
@endif


@if(\Auth::user()->permission_id == 1 || \Auth::user()->permission_id == 2)
    @include('backend.auditor.warning')
@endif --}}


@endsection

resources/views/backend/unggah/jquery.blade.php
$(document).ready(function(){
    $(document).on("click",".ubah",function() {
    adanLoadingFadeIn();
        var id = $(this).attr('data-id');
        $.loadmodal({
            url: "{{ url($url_admin.'/unggah') }}/"+ id +"/edit",
        id: 'responsive',
            dlgClass: 'fade',
            bgClass: 'warning',
            title: 'Ubah',
            width: '700px',
            modal: {
                keyboard: true,
                // any other options from the regular $().modal call (see Bootstrap docs)
                },
            ajax: {
                dataType: 'html',
                method: 'GET',
                success: function(data, status, xhr){
            adanLoadingFadeOut();
                },
            },
        });
    });

    $(document).on("click",".unggah",function() {
    adanLoadingFadeIn();
    var id = $(this).attr('data-id');
		$.loadmodal({
			url: "{{ url($url_admin.'/unggah/modal_unggah') }}/"+ id,
            id: 'responsive',
			dlgClass: 'fade',
			bgClass: 'success',
			title: 'Unggah',
			width: '700px',
			modal: {
				keyboard: true,
				// any other options from the regular $().modal call (see Bootstrap docs)
				},
          ajax: {
				dataType: 'html',
				method: 'GET',
				success: function(data, status, xhr){
            adanLoadingFadeOut();
				},
			},
        });
	});

    $(document).on("click",".hapus",function() {
    adanLoadingFadeIn();
        var id = $(this).attr('data-id');
        $.loadmodal({
            url: "{{ url($url_admin.'/unggah/hapus') }}/"+ id,
        id: 'responsive',
            dlgClass: 'fade',
            bgClass: 'danger',
            title: 'Hapus',
            width: '300px',
            modal: {
                keyboard: true,
                // any other options from the regular $().modal call (see Bootstrap docs)
                },
            ajax: {
                dataType: 'html',
                method: 'GET',
                success: function(data, status, xhr){
            adanLoadingFadeOut();
                },
            },
        });
    });

});

resources/views/backend/unggah/ubah.blade.php
<link href="{{ URL::asset('assets/plugins/fileuploads/css/fileupload.css')}}" rel="stylesheet" />

{!! Form::open(array('id' => 'frmAdan-ubah', 'class' => 'form account-form', 'method' => 'PUT')) !!}
{{ csrf_field() }}
<div class="row">
	<div class="col-md-12">
        <div class="form-group row">
            {!! Form::label('Jenis Dokumen', 'Jenis Dokumen *', array('class' => 'col-md-4 form-label')) !!}
            <div class="col-md-12">
            {!! Form::select('jenis', ['Berita Acara'=>'Berita Acara', 'Laporan'=>'Laporan'], $data->jenis, array('id' => 'jenis', 'class' => 'form-control select2', 'placeholder' => 'Pilih', 'style' => 'width:100%')) !!}
            </div>
        </div>

		{!! Form::hidden('url', URL::previous(), array('id' => 'url')) !!}
	    {!! Form::hidden('id', $data->id, array('id' => 'id')) !!}

		<div class="form-group row">
			<div class="col-md-12">
				<span class="pesan"></span>
			</div>
		</div>

	</div>
</div>

{!! Form::close() !!}
<script src="{{ URL::asset('adan/unggah/ajax.js') }}"></script>
<script src="{{ URL::asset('adan/script/ajax.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/fileuploads/js/fileupload.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/fileuploads/js/file-upload.js') }}"></script>

resources/views/backend/unggah/unggah.blade.php
<link href="{{ URL::asset('assets/plugins/fileuploads/css/fileupload.css')}}" rel="stylesheet" />

{!! Form::open(array('id' => 'frmAdan', 'class' => 'form account-form', 'method' => 'PUT')) !!}
{{ csrf_field() }}
<div class="row">
	<div class="col-md-12">
        <div class="form-group row">
            {!! Form::label('Jenis Dokumen', 'Jenis Dokumen *', array('class' => 'col-md-4 form-label')) !!}
            <div class="col-md-12">
            {!! Form::select('jenis', ['Berita Acara'=>'Berita Acara', 'Laporan'=>'Laporan'], NULL, array('id' => 'jenis', 'class' => 'form-control select2', 'placeholder' => 'Pilih', 'style' => 'width:100%')) !!}
            </div>
        </div>
        <div class="form-group">
            <label class="form-label">Bagikan link file Google Drive</label>
            <input type="text" class="form-control" name="urlfile" id="urlfile" placeholder="https://drive.google.com/file/d/1prmuzkpeRoD7UeqTvQSmWV__yAhjp96C/view?usp=sharing">
        </div>
		{{-- <div class="form-group row">
			{!! Form::label('Unggah Dokumen', 'Unggah Dokumen', array('class' => 'col-md-4 form-label')) !!}
			<div class="col-md-12">
			{!! Form::file('pic', array('id' => 'pic', 'class' => 'dropify', 'data-height' => '300')) !!}
			</div>
		</div> --}}
		{!! Form::hidden('url', URL::previous(), array('id' => 'url')) !!}
		<div class="form-group row">
			<div class="col-md-12">
				<span class="pesan"></span>
			</div>
		</div>

	</div>
</div>

{!! Form::close() !!}
<script src="{{ URL::asset('adan/unggah/ajax.js') }}"></script>
<script src="{{ URL::asset('adan/script/ajax.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/fileuploads/js/fileupload.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/fileuploads/js/file-upload.js') }}"></script>